# Generated by Django 2.1.4 on 2019-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt180', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='univertite',
            new_name='universite',
        ),
        migrations.AddField(
            model_name='candidat',
            name='email',
            field=models.EmailField(default='jjki@jojo.loi', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='theme',
            field=models.TextField(max_length=500),
        ),
    ]
