# Generated by Django 2.1.4 on 2019-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt180', '0002_auto_20190223_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='theme',
            field=models.TextField(),
        ),
    ]
